---

- name: "grab the custom hiera tuning profile for {{ ansible_facts['memory_mb']['real']['total'] | int / 1024 | int }}GB"
  get_url:
    url: https://raw.githubusercontent.com/RedHatSatellite/satellite-support/master/tuning-profiles/{{ tuning_heira }}
    dest: /etc/foreman-installer/custom-hiera.yaml
    owner: root
    group: root
    mode: '0644'
    force: true
  notify: rerun_satellite_installer

- name: create httpd service directory
  file:
    path: /etc/systemd/system/httpd.service.d
    state: directory

- name: push satellite tuning config files
  template:
    src: "templates/{{ config_file.name }}"
    dest: "{{ config_file.path }}"
    owner: root
    group: root
    mode: '0644'
  loop_control:
    loop_var: config_file
  with_items:
    - "{{ satellite.tuning_config_files }}"
  notify:
    - reload_systemd
    - restart_satellite
    - reload_kernel_params
