---

- name: set tuning size | 32GB
  set_fact:
    tuning_heira: custom-hiera-medium-32G.yaml
  when:
    - ansible_facts['memory_mb']['real']['total'] | int >= 32768
    - ansible_facts['memory_mb']['real']['total'] | int < 65536

- name: set tuning size | 64GB
  set_fact:
    tuning_heira: custom-hiera-large-64G.yaml
  when:
    - ansible_facts['memory_mb']['real']['total'] | int >= 65536
    - ansible_facts['memory_mb']['real']['total'] | int < 131072

- name: set tuning size | 128GB
  set_fact:
    tuning_heira: custom-hiera-ex-large-128G.yaml
  when:
    - ansible_facts['memory_mb']['real']['total'] | int >= 131072
    - ansible_facts['memory_mb']['real']['total'] | int < 262144

- name: set tuning size | 256GB
  set_fact:
    tuning_heira: custom-hiera-2ex-large-256G.yaml
  when:
    - ansible_facts['memory_mb']['real']['total'] | int >= 262144

- include_tasks: push-satellite-tuning-configs.yml
  when:
    - tuning_heira is defined

- name: flush handlers
  meta: flush_handlers
