---

- name: upload manifest
  theforeman.foreman.katello_manifest:
    username: "{{ satellite.admin_username }}"
    password: "{{ satellite.admin_password }}"
    validate_certs: false
    server_url: "{{ satellite_url }}"
    organization: "{{ organization.organization_name }}"
    state: present
    manifest_path: "{{ organization.manifest }}"
  delegate_to: "{{ delegate_host }}"
